version: '3.9'
#Purawat Verukanjana 645162010023
#0023
#9923

services:
  sv_db:
    image: purawatzero/dpu_ct519_lab_exam:img_mariadb
    container_name: ctn_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: purawat.v.password
      MARIADB_USER: purawat.v.user
      MARIADB_PASSWORD: purawat.v.password
      MARIADB_DATABASE: 0023_Lab_Exam
    volumes:
      - ./App_A/mariadb:/var/lib/mysql
    networks:
      app_net:
    ports:
      - "3306:3306"

  sv_dbadmin:
    image: purawatzero/dpu_ct519_lab_exam:img_adminer
    container_name: ctn_adminer
    restart: always
    networks:
      app_net:
    ports:
      - "8081:8080"
    
  sv_webphp:
    image: purawatzero/dpu_ct519_lab_exam:img_php
    container_name: ctn_php
    restart: always
    networks:
      app_net:
    volumes:
      - ./App_A/www/:/var/www/html
      - ./App_A/php/conf.d/:/usr/local/etc/php/conf.d
      - ./App_A/php/lib/:/usr/local/lib/php
    links:
      - "sv_db:database"
    ports:
      - "80:80"

  sv_webgo:
    image: purawatzero/dpu_ct519_lab_exam:img_golang
    container_name: ctn_golang
    volumes:
      - ./App_B/:/go/src
      - ./App_B/www/:/go/src/www
    working_dir: /go/src
    command: 'go run main.go'
    # command: 'sleep 7200'
    ports:
      - "9923:8080"
    expose:
      - "9923"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
